### PR TITLE
revive the project a bit

### PR DESCRIPTION
**Pull request by lygaret**
This PR:

* merges #3 
* gets the library working against recent rack and ruby 3
* applies `standardrb` code formatter

I'm basing some new code off of this.

I'm wondering about whether this project could come back some; I really like it's simplicity, and I think there's a very small handful of features that could be added that could make it a goto, at least fo a certain type of project.

I have a couple more PRs I'm working that are based off of this one; I'm happy to leave everything on my fork, but if we could get some of this moving together I think that would be rad!

- Jon

### CODE REVIEW

**Comment by lygaret** [comment]
I'm also very happy to undo the code formatter, but leave the rack/ruby 3 updates, let me know

**Comment by guilleiguaran** [comment]
@lygaret I'll add you as contributor to the project

**Comment by lygaret** [comment]
> @lygaret I'll add you as contributor to the project

This is great, thank you! I was happy to see these get merged today! Is there anything you've got planned in particular? I can open issues with things I've thought about, though I'll be honest that I haven't used this outside of small personal projects.

**Comment by guilleiguaran** [comment]
@lygaret feel free to open the issues and I'll review them!!

**Pull request merged**
